"""add_backtest_run_table

Revision ID: 02e17fa55787
Revises: 0e6ebfdb000c
Create Date: 2025-11-18 03:42:14.844500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e17fa55787'
down_revision = '0e6ebfdb000c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_logs', 'input_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('agent_logs', 'output_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('agent_logs', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_logs', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('agent_logs', 'output_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('agent_logs', 'input_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###