"""add decision_type and strategy_name to agent_logs

Revision ID: 34ca5d20d731
Revises: 02e17fa55787
Create Date: 2025-12-07 02:35:42.556824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ca5d20d731'
down_revision = '02e17fa55787'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_logs', sa.Column('decision_type', sa.String(length=20), nullable=True))
    op.add_column('agent_logs', sa.Column('strategy_name', sa.String(length=50), nullable=True))
    op.alter_column('agent_logs', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_agent_logs_decision_type'), 'agent_logs', ['decision_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_logs_decision_type'), table_name='agent_logs')
    op.alter_column('agent_logs', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('agent_logs', 'strategy_name')
    op.drop_column('agent_logs', 'decision_type')
    # ### end Alembic commands ###