"""add_risk_fields_to_recommendations

Revision ID: 54096cbc2ec2
Revises: 75b2bddab449
Create Date: 2025-12-08 02:00:46.983332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54096cbc2ec2'
down_revision = '75b2bddab449'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_recommendations', sa.Column('stop_loss', sa.Float(), nullable=True))
    op.add_column('agent_recommendations', sa.Column('take_profit', sa.Float(), nullable=True))
    op.add_column('agent_recommendations', sa.Column('position_size_pct', sa.Float(), nullable=True))
    op.add_column('agent_recommendations', sa.Column('time_horizon', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_recommendations', 'time_horizon')
    op.drop_column('agent_recommendations', 'position_size_pct')
    op.drop_column('agent_recommendations', 'take_profit')
    op.drop_column('agent_recommendations', 'stop_loss')
    # ### end Alembic commands ###