"""add_agent_recommendations_table

Revision ID: 75b2bddab449
Revises: d30e130602ac
Create Date: 2025-12-08 00:22:24.926327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b2bddab449'
down_revision = 'd30e130602ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paper_orders', 'binance_order_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paper_orders', 'binance_order_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###