"""add_paper_orders_table

Revision ID: d30e130602ac
Revises: 34ca5d20d731
Create Date: 2025-12-07 07:59:07.577802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30e130602ac'
down_revision = '34ca5d20d731'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###